### ISSUE TITLE
Enable HTTP/2 in nginx conf

### ISSUE THREAD

**Issue by danielsamuels** [onespacemedia/server-management#23]
Requires a newer version of nginx, not sure if it's available via apt-get.

http://caniuse.com/#feat=http2
https://www.nginx.com/blog/nginx-1-9-5/

**Comment by danielsamuels** [comment]
Can use this to get the latest version of nginx stable, we should probably do this: http://serverfault.com/a/665984

**Comment by danielsamuels** [comment]
https://by-example.org/install-nginx-with-http2-support-on-ubuntu-14-04-lts/

**Comment by danielsamuels** [comment]
https://gist.github.com/Globegitter/685e3739c0f181bda3ec

**Comment by dan-gamble** [comment]
What's the support like on this currently?

**Comment by danielsamuels** [comment]
Pretty good! http://caniuse.com/#feat=http2

**Comment by lewiscollard** [comment]
Bear in mind this has a dependency on #4 - all browsers that support HTTP/2 require encrypted connections when using it. Would this have to be done as a separate management command from `deploy`?

**Comment by danielsamuels** [comment]
It's a bit of a chicken and egg situation.  What I'd probably do is install the latest version of nginx as part of the regular deploy process, and then enable HTTP/2 as part of the `setup_ssl` command.  I think the only real change is changing `listen 443` to `listen 442 http2` or something. It's simple, whatever it is.

**Comment by lewiscollard** [comment]
That is a good idea.

**Comment by danielsamuels** [comment]
Fixed on the [http2-lets-encrypt](https://github.com/onespacemedia/server-management/tree/http2-lets-encrypt) branch.
