### ISSUE TITLE
Make `deploy` work on Debian Jessie (current stable)

### ISSUE THREAD

**Issue by lewiscollard** [onespacemedia/server-management#44]
If nothing else, it gives us options if Ubuntu ever does something terrible, and supporting one extra Debian variant makes it easier to support others.

`deploy` almost worked perfectly, with these tweaks:

* Install `aptitude` manually (it is by default on Ubuntu, but not Debian - needs to be done before any other packages are installed)
* Install `ufw` (it's not by default on Debian)
* Make it install postgresql 9.4 rather than 9.3 if deploying to Jessie, as Jessie doesn't have 9.3.
* `pg_tune` does not exist in jessie, so skip this step in case of a Jessie system (and so the 'Backuping PostgreSQL main config file' task should not be run either)
* `dpkg-reconfigure` locales takes a very long time and I suspect it's actually being run interactively (it's non-interactive on Ubuntu) - see https://serverfault.com/questions/362903/how-do-you-set-a-locale-non-interactively-on-debian-ubuntu
* A `sudo systemctl daemon-reload` is necessary to get postgresql to start (a `service postgresql restart` might be necessary after that). I don't know why.
* Debian's SSH is a bit more finicky; it won't allow SSH connections if someone's home directory is writable. 750 on the home directory and 700 on everything, recursively, on `.ssh` fixes this.

**Comment by danielsamuels** [comment]
> Install `aptitude` manually (it is by default on Ubuntu, but not Debian - needs to be done before any other packages are installed)

I ran `apt-get install aptitude` on my Ubuntu 16.04 instance and it's trying to install it.  Should it be getting installed on Ubuntu too?

> Install ufw (it's not by default on Debian)

Added on my branch.

> Make it install postgresql 9.4 rather than 9.3 if deploying to Jessie, as Jessie doesn't have 9.3.

I've changed it to just install `postgresql` so we don't have to define the version, it'll just take the latest.

> pg_tune does not exist in jessie, so skip this step in case of a Jessie system (and so the 'Backuping PostgreSQL main config file' task should not be run either)

I'm going to remove `pg_tune` completely, I'm not sure if it really makes a difference for us.  If it causes slowdowns we can re-evaluate.

> dpkg-reconfigure locales takes a very long time and I suspect it's actually being run interactively 

Interactive in Ubuntu 16.04 too, fixed in my branch.

> A sudo systemctl daemon-reload is necessary to get postgresql to start (a service postgresql restart might be necessary after that). I don't know why.

Still TODO on my branch.

> Debian's SSH is a bit more finicky; it won't allow SSH connections if someone's home directory is writable. 750 on the home directory and 700 on everything, recursively, on .ssh fixes this.

Fixed on my branch. I went with these:

```chmod 0750 ~deploy
chmod 0700 ~deploy/.ssh
chmod 0600 ~deploy/.ssh/id_rsa
chmod 0644 ~deploy/.ssh/id_rsa.pub
chown deploy:webapps ~deploy/.ssh/authorized_keys```

**Comment by lewiscollard** [comment]
> I ran apt-get install aptitude on my Ubuntu 16.04 instance and it's trying to install it. Should it be getting installed on Ubuntu too?

Seems like it's not installed by default on 16.04, https://askubuntu.com/questions/765284/16-04-aptitude-at-the-command-line

**Comment by danielsamuels** [comment]
Does it need to be?

**Comment by lewiscollard** [comment]
Perhaps not. As our servers tend to be frozen in their initial configuration, [the advantages](https://askubuntu.com/questions/1743/is-aptitude-still-considered-superior-to-apt-get) of `aptitude` over a plain ol' `apt-get ` don't really apply:

> aptitude adds explicit per-package flags, indicating whether a package was automatically installed to satisfy a dependency: you can manipulate those flags (aptitude markauto or aptitude unmarkauto) to change the way aptitude treats the package.
> apt-get keeps track of the same information, but will not show it explicitly. apt-mark can be used for manipulating the flags.
> aptitude will offer to remove unused packages each time you remove an installed package, whereas apt-get will only do that if explicitly asked to with apt-get autoremove or specify --auto-remove.

For our purposes I think we could just switch out usage of `aptitude` with `apt-get` and its friends.

**Comment by danielsamuels** [comment]
Well that's the thing, I don't think we're actually using it.  I wonder if Ansible was using it under the hood for something?

Either way, seems we can skip that one.  Interesting that you can just use `apt` in place of `apt-get` on 16.04, though I imagine it might be useful to maintain backwards compatibility.

**Comment by lewiscollard** [comment]
> Well that's the thing, I don't think we're actually using it. I wonder if Ansible was using it under the hood for something?

I was starting to doubt my sanity when I didn't see aptitude anywhere in `deploy.py` - yes, I think this is the case :)

**Comment by danielsamuels** [comment]
[Confirmed](https://github.com/ansible/ansible-modules-core/blob/6972d0a2916caa931030fbb593d100e433477c96/packaging/os/apt.py#L530)!
