### ISSUE TITLE
Update script: should gunicorn always be installed?

### ISSUE THREAD

**Issue by lewiscollard** [onespacemedia/server-management#47]
Right now, the update script checks for changes in `requirements.txt`, and if there are changes it nukes the venv, rebuilds it, and installs gunicorn.

However, this means that if a manual nuking and rebuild of the virtual environment is necessary, and no changes are made in `requirements.txt` in a given update, `gunicorn` will never be installed. As the check is so quick, is it worth installing `gunicorn` on every update, or is this just handling a very rare edge case (nuking/rebuild of the venv in which `gunicorn` was not manually installed)?

**Comment by danielsamuels** [comment]
I think it is a rare edge case, but there's also so little overhead in running `pip install gunicorn` each time that I don't really have anything against it.

**Comment by lewiscollard** [comment]
Fixed in 6a8d1463cc4
