### ISSUE TITLE
Investigate zero downtime deploys

### ISSUE THREAD

**Issue by danielsamuels** [onespacemedia/server-management#55]

**Comment by danielsamuels** [comment]
Supervisor 3.2 [added support for sending signals to worker processes](https://github.com/Supervisor/supervisor/issues/53#issuecomment-162905711). It seems that we're using version 3.0b2, which is the version you get when installing via apt.  To get the latest version (3.3.3 as of writing) we need to install via pip (`sudo pip install supervisor`).

**Comment by danielsamuels** [comment]
`$ sudo supervisorctl signal HUP cambridge_wireless` will reload the application code without downtime. Removing the venv is still problematic though.

**Comment by danielsamuels** [comment]
I'm wondering if we could solve the venv issue by having a venv named according to the commit hash which it corresponds to, and then symlinking the `.venv` folder to it.

**Comment by dan-gamble** [comment]
What's the reason behind `.venv` rebuilding even when theres no reqs.txt changes? I remember we added it for a reason, just can't remember what.

**Comment by danielsamuels** [comment]
Useful resources:

* https://medium.com/@healthchecks/deploying-a-django-app-with-no-downtime-f4e02738ab06
* https://medium.com/@prabhavjain/adventures-with-gunicorn-supervisor-graceful-reload-on-code-changes-a13b221d946b

**Comment by danielsamuels** [comment]
> What's the reason behind .venv rebuilding even when theres no reqs.txt changes? I remember we added it for a reason, just can't remember what.

I think it's because if a previous build fails then you get left in a state where you have no venv, or at least not a usable one.
