### ISSUE TITLE
pushmedia having problems due to permissions

### ISSUE THREAD

**Issue by danielsamuels** [onespacemedia/server-management#60]
You SSH in and rsync as `deploy`, but the `_media` files and folders need to be owned by the project user, this causes problems.

**Comment by lewiscollard** [comment]
Could it be [this simple](https://askubuntu.com/a/719440)?

Maybe we could try `rsync --rsync-path='sudo -u webapp_user rsync' .....` so long as `webapp_user` has write permissions to the media directory (which should always be the case?).

**Comment by danielsamuels** [comment]
Looks reasonable, the project user doesn't have sudo by default though.

**Comment by lewiscollard** [comment]
That should be fine - you'd still be shelling in as `deploy`, but `--rsync-path` in this case would immediately sudo to the project user to do the copy on the other end. I'm going to actually try this first though. :)

**Comment by lewiscollard** [comment]
Confirmed it works - shall I push this onto `various-fixes` or start a new one?

**Comment by danielsamuels** [comment]
various-fixes would be best, as I've made changes to pushmedia in there already
